In [1]:
import numpy as np
from PythonAPI.bam import BAM

In [2]:
dataset_dir = '/home/almartmen/Github/bonn_activity_maps/aikapi' 
dataset_name = '181129'

bam = BAM(dataset_dir, dataset_name, image_format='png')

Reading dataset information...
Loading calibration parameters...
     camera00.json...
     camera01.json...
     camera02.json...
     camera03.json...
     camera04.json...
     camera05.json...
     camera06.json...
     camera07.json...
     camera08.json...
     camera09.json...
     camera10.json...
     camera11.json...
Loading annotations...
Processing persons...
Processing objects...
Processing actions...
Finish loading dataset


First, lets test the distance with box AIK objects

In [3]:
box_points = np.asarray([[0,0,1],[1,0,1],[0,1,0]])

In [4]:
point_1 = np.asarray([2,0,0])
point_2 = np.asarray([0.5, 0.5, 0.5])
point_3 = np.asarray([0.5, 0.5, 3])
point_4 = np.asarray([0, 0.5, 0.5])
point_5 = np.asarray([-0.1, 0.5, 0.5])
point_6 = np.asarray([2,0.5,2])

In [5]:
distance_1 = bam.distance_to_static_object("boxAIK", box_points, point_1)
distance_2 = bam.distance_to_static_object("boxAIK", box_points, point_2)
distance_3 = bam.distance_to_static_object("boxAIK", box_points, point_3)
distance_4 = bam.distance_to_static_object("boxAIK", box_points, point_4)
distance_5 = bam.distance_to_static_object("boxAIK", box_points, point_5)
distance_6 = bam.distance_to_static_object("boxAIK", box_points, point_6)

In [6]:
print(distance_1)
print(distance_2)
print(distance_3)
print(distance_4)
print(distance_5)
print(distance_6)

[-1.  0.  0.]
[0, 0, 0]
[ 0.  0. -2.]
[0. 0. 0.]
[0.1 0.  0. ]
[-1.  0. -1.]


Now, lets test the distances with cylinder AIK objects

In [7]:
cylinder_points = np.asarray([[1,1,2], [2,1,2]])

In [8]:
point_1 = np.asarray([0.5,0.5,4])
point_2 = np.asarray([4, 1, 1])
point_3 = np.asarray([2.5, 1, 2])
point_4 = np.asarray([2.5, 1, 3])

In [9]:
distance_1 = bam.distance_to_static_object("cylinderAIK", cylinder_points, point_1)
distance_2 = bam.distance_to_static_object("cylinderAIK", cylinder_points, point_2)
distance_3 = bam.distance_to_static_object("cylinderAIK", cylinder_points, point_3)
distance_4 = bam.distance_to_static_object("cylinderAIK", cylinder_points, point_4)

In [10]:
print(distance_1)
print(distance_2)
print(distance_3)
print(distance_4)

[ 0.  0. -2.]
[-2.  0.  0.]
[-0.5  0.   0. ]
[-0.5  0.  -1. ]
