In [1]:
import numpy as np
from PythonAPI.aik import AIK
from PythonAPI.utils.camera import Camera

Define the absolute path to the dataset and the dataset name.

Create AIK object to load the dataset:

- All the annotations will be loaded into memory and processed.
- The videos are unrolled in png images by default, but the format can be changed to jpeg.

In [2]:
# dataset_dir = '/home/beatriz/Documentos/Work' # Your path
dataset_dir = '/home/almartmen/Github/aikapi' 
dataset_name = '181129'

aik = AIK(dataset_dir, dataset_name, image_format='png')

Reading dataset information...
Loading calibration parameters...
     camera00.json...
     camera01.json...
     camera02.json...
     camera03.json...
     camera04.json...
     camera05.json...
     camera06.json...
     camera07.json...
     camera08.json...
     camera09.json...
     camera10.json...
     camera11.json...
Loading annotations...
Processing persons...
Processing actions...
Finish loading dataset


Get Camera object for camera 3 and frame 1 (Camera usage example can be found below)

In [3]:
camera = aik.get_camera(3,1)
print(camera.to_json())

{"K": [[1059.111083984375, 0.0, 638.343994140625], [0.0, 1058.1497802734375, 394.7500305175781], [0.0, 0.0, 1.0]], "P": [[-745.3416037397837, -970.7086534756199, -170.29725224389983, 4867.531825297799], [48.999378047246864, -99.75383605078969, -1122.3262807831234, 2640.7506968589573], [0.36730334162712097, -0.894257664680481, -0.25571754574775696, 5.646644722770345]], "rvec": [0.4403006434440613, -2.2728705406188965, 1.7474119663238525], "tvec": [1.196131706237793, 0.39258167147636414, 5.646644592285156], "distCoef": [0.0, 0.0, 0.0, 0.0, 0.0], "w": 1280, "h": 720}


Get an array with all persons annotated in frame 1000

In [4]:
print(aik.get_persons_in_frame(1000))

{'pid': 1, 'location': [[0.498339264765202, 3.2171029078369897, 1.5828869056621102]]}
{'pid': 1, 'location': [[0.4467057519225968, 3.190209666835337, 1.6002512333266694]]}


KeyError: 'type'

Get an array with all poses annotated in frame 1000

In [6]:
print(aik.get_poses_in_frame(1000))

KeyError: 'type'

Get the annotated person with pid 1 in frame 999

In [7]:
points3d_person = aik.get_person_in_frame(999, 1)
print(points3d_person)

KeyError: 'type'

Get the pose for person with pid 1 in frame 999

In [8]:
points3d_pose = aik.get_pose_in_frame(999, 1)
print(points3d_pose)

KeyError: 'type'

Using Camera object to project 3D points into the 2D image plane

In [9]:
points2d_person = camera.project_points(points3d_person)
print(points2d_person)

NameError: name 'points3d_person' is not defined

Using Camera object to project 3D points of the pose into the 2D image plane

In [10]:
points2d_pose = camera.project_points(points3d_pose)
print(points2d_pose)

NameError: name 'points3d_pose' is not defined

Get an array with all activities for person with pid 2

In [11]:
print(aik.get_activities_for_person(2))

[{'label': 'carry plate', 'start_frame': 2271, 'end_frame': 2367}
 {'label': 'carry cake', 'start_frame': 2647, 'end_frame': 2739}
 {'label': 'carry cup', 'start_frame': 1009, 'end_frame': 1187}
 {'label': 'open fridge', 'start_frame': 1197, 'end_frame': 1229}
 {'label': 'take cake out of fridge', 'start_frame': 1245, 'end_frame': 1345}
 {'label': 'carry cake', 'start_frame': 1271, 'end_frame': 1387}
 {'label': 'close fridge', 'start_frame': 1333, 'end_frame': 1363}
 {'label': 'place cake on table', 'start_frame': 1387, 'end_frame': 1399}
 {'label': 'open drawer', 'start_frame': 1531, 'end_frame': 1571}
 {'label': 'close drawer', 'start_frame': 1607, 'end_frame': 1649}
 {'label': 'cut cake in pieces', 'start_frame': 1723, 'end_frame': 2105}
 {'label': 'open cupboard', 'start_frame': 2133, 'end_frame': 2159}
 {'label': 'close cupboard', 'start_frame': 2159, 'end_frame': 2199}
 {'label': 'open cupboard', 'start_frame': 2223, 'end_frame': 2253}
 {'label': 'close cupboard', 'start_frame': 

Unroll videos using the format indicated in the constructor (This may take a while):
- By default, all videos are unrolled and if the frames already exists, they are not overwritten
- In order to unroll only one video, you can use the parameter video=X
- If you want to overwrite the existing frames, you have to use force=True

If the videos are not unrolled before getting the individual frames, then they will be automatically unrolled when you try to get the frames.

In [46]:
aik.unroll_videos()
#aik.unroll_videos(force=True)             # Force to overwrite unrolled frames
#aik.unroll_videos(video=2)                # Unroll only video 2
#aik.unroll_videos(force=True, video=2)    # Force to overwrite frames of video 2 if they already exist

The videos are already unrolled. If you want to unroll them again and overwrite the current frames, please use the option force=True


Get images from 12 cameras for frame 1.


In [12]:
print(aik.get_images_in_frame(1))

Searching for images of frame  1 ...
Frame name: frame000000001.png
Images of frame  1  retrieved.
[[[[231 249 248]
   [237 255 254]
   [235 250 250]
   ...
   [ 63  61  57]
   [ 63  61  57]
   [ 63  61  57]]

  [[235 253 252]
   [237 255 254]
   [236 251 251]
   ...
   [ 63  61  57]
   [ 63  61  57]
   [ 63  61  57]]

  [[241 255 255]
   [240 255 255]
   [238 253 253]
   ...
   [ 63  61  57]
   [ 63  61  57]
   [ 63  61  57]]

  ...

  [[ 79  77  71]
   [ 79  77  71]
   [ 79  77  71]
   ...
   [228 192 134]
   [220 184 126]
   [217 181 123]]

  [[ 79  77  71]
   [ 79  77  71]
   [ 79  77  71]
   ...
   [225 189 131]
   [217 181 123]
   [212 176 118]]

  [[ 79  77  71]
   [ 79  77  71]
   [ 79  77  71]
   ...
   [222 186 128]
   [215 179 121]
   [211 175 117]]]


 [[[115 110 105]
   [115 110 105]
   [113 108 103]
   ...
   [117 113  94]
   [117 113  94]
   [117 113  94]]

  [[115 110 105]
   [115 110 105]
   [113 108 103]
   ...
   [117 113  94]
   [117 113  94]
   [117 113  94]]

  [[

Get all the available person IDs existing in the dataset.

In [13]:
print(aik.get_person_ids())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
