In [36]:
import numpy as np
from PythonAPI.aik import AIK
from PythonAPI.utils.camera import Camera

Define the absolute path to the dataset and the dataset name.

Create AIK object to load the dataset:

- All the annotations will be loaded into memory and processed.
- The videos are unrolled in png images by default, but the format can be changed to jpeg.

In [37]:
dataset_dir = '/home/beatriz/Documentos/Work' # Your path
dataset_name = '181129'

aik = AIK(dataset_dir, dataset_name, image_format='png')

Reading dataset information...
Loading calibration parameters...
     camera00.json...
     camera01.json...
     camera02.json...
     camera03.json...
     camera04.json...
     camera05.json...
     camera06.json...
     camera07.json...
     camera08.json...
     camera09.json...
     camera10.json...
     camera11.json...
Loading annotations...
Processing persons...
Processing actions...
Finish loading dataset


Get Camera object for camera 3 and frame 1 (Camera usage example can be found below)

In [38]:
camera = aik.get_camera(3,1)
print(camera.to_json())

{"K": [[1059.111083984375, 0.0, 638.343994140625], [0.0, 1058.1497802734375, 394.7500305175781], [0.0, 0.0, 1.0]], "P": [[-745.3416037397837, -970.7086534756199, -170.29725224389983, 4867.531825297799], [48.999378047246864, -99.75383605078969, -1122.3262807831234, 2640.7506968589573], [0.36730334162712097, -0.894257664680481, -0.25571754574775696, 5.646644722770345]], "rvec": [0.4403006434440613, -2.2728705406188965, 1.7474119663238525], "tvec": [1.196131706237793, 0.39258167147636414, 5.646644592285156], "distCoef": [0.0, 0.0, 0.0, 0.0, 0.0], "w": 1280, "h": 720}


Get an array with all persons annotated in frame 1000

In [39]:
print(aik.get_persons_in_frame(1000))

[{'pid': 1, 'location': [[0.4725225083438994, 3.2036562873361634, 1.5915690694943898]], 'type': 'personAIK'}]


Get an array with all poses annotated in frame 1000

In [40]:
print(aik.get_poses_in_frame(1000))

[{'pid': 1, 'location': [[0.4940468668937683, 3.0975520610809326, 1.5879707336425781], [0.33225908875465393, 3.3022162914276123, 1.4874387979507446], [0.248513141442759, 3.1166828037377776, 1.4797768626685919], [0.20898175630705926, 3.074002764986737, 1.1761494834683632], [0.4430496301335054, 3.003187955078469, 1.0902041995243112], [0.38873064050115674, 3.427037257731697, 1.496395562953885], [0.3684694009394898, 3.523452423490153, 1.2177340325466113], [0.491342276987256, 3.4243839963247877, 1.097171939112425], [0.23896421401011708, 3.189862974200601, 0.9370316866970752], [0.24986874568797326, 3.1303426266153522, 0.554225104984327], [0.1988182237148894, 3.1238738197003224, 0.13678569408919353], [0.3448095801460418, 3.369042606439794, 0.9246938349214029], [0.338286297862635, 3.3997655290610216, 0.5305125781965845], [0.26704269329099944, 3.4579307929059104, 0.12287995423906839], [0.4640180468559265, 3.098863124847412, 1.620947539806366], [0.5159120857715607, 3.104530453681946, 1.613197445

Get the annotated person with pid 1 in frame 999

In [41]:
points3d_person = aik.get_person_in_frame(999, 1)
print(points3d_person)

[[0.49833926 3.21710291 1.58288691]]


Get the pose for person with pid 1 in frame 999

In [42]:
points3d_pose = aik.get_pose_in_frame(999, 1)
print(points3d_pose)

[[0.5035534501075745 3.130488157272339 1.5877115726470947]
 [0.33670544624328613 3.3233115673065186 1.4915584325790405]
 [0.2601630934244206 3.1344935528657083 1.4807234524039452]
 [0.23090367223047764 3.0881537576408444 1.1747466193888727]
 [0.4624710651429028 3.029305688118087 1.0831168845064802]
 [0.3856729454498077 3.455096568910931 1.4978647658373092]
 [0.3619406195839864 3.5508452311951317 1.2187215628731682]
 [0.4886760044595372 3.4570746179859917 1.0985927148803882]
 [0.24285354310399074 3.209109735748986 0.937708336249335]
 [0.25412233062007106 3.1515303312903313 0.5549463394038321]
 [0.20223532605420524 3.136944223773778 0.1367580121232862]
 [0.34022819265764337 3.3945968087010883 0.9251715573337408]
 [0.331675231308763 3.423327599530494 0.525658220126438]
 [0.26221012966169743 3.468437276697019 0.11578491871101904]
 [0.47325873374938965 3.134596586227417 1.6200170516967773]
 [0.5254986882209778 3.126495838165283 1.611875295639038]
 [0.3865627348423004 3.2179574966430664 1.66

Using Camera object to project 3D points into the 2D image plane

In [43]:
points2d_person = camera.project_points(points3d_person)
print(points2d_person)

[[433.4901123 223.1262207]]


Using Camera object to project 3D points of the pose into the 2D image plane

In [44]:
points2d_pose = camera.project_points(points3d_pose)
print(points2d_pose)

[[450.8388366699219 217.81466674804688]
 [470.61767578125 270.0149841308594]
 [538.8987426757812 265.5368347167969]
 [561.4820556640625 384.7188720703125]
 [494.21343994140625 405.29412841796875]
 [419.7138671875 274.1397399902344]
 [411.8172912597656 409.0498046875]
 [391.7168884277344 443.5646667480469]
 [537.956298828125 488.101806640625]
 [548.814697265625 618.168212890625]
 [572.6828002929688 759.2857666015625]
 [464.9683837890625 513.0198974609375]
 [469.81256103515625 671.6459350585938]
 [492.6123046875 834.9786376953125]
 [459.8658752441406 205.0677032470703]
 [443.5933532714844 207.6044158935547]
 [472.044921875 189.6732635498047]
 [392.3619689941406 197.2364501953125]
 [439.4338684082031 823.7847290039062]
 [None None]
 [498.9254150390625 868.6483764648438]
 [550.8798828125 717.7140502929688]
 [561.549560546875 730.377685546875]
 [577.42626953125 774.226806640625]]


Get an array with all activities for person with pid 2

In [45]:
print(aik.get_activities_for_person(2))

[{'label': 'carry plate', 'start_frame': 2271, 'end_frame': 2367}
 {'label': 'carry cake', 'start_frame': 2647, 'end_frame': 2739}
 {'label': 'carry cup', 'start_frame': 1009, 'end_frame': 1187}
 {'label': 'open fridge', 'start_frame': 1197, 'end_frame': 1229}
 {'label': 'take cake out of fridge', 'start_frame': 1245, 'end_frame': 1345}
 {'label': 'carry cake', 'start_frame': 1271, 'end_frame': 1387}
 {'label': 'close fridge', 'start_frame': 1333, 'end_frame': 1363}
 {'label': 'place cake on table', 'start_frame': 1387, 'end_frame': 1399}
 {'label': 'open drawer', 'start_frame': 1531, 'end_frame': 1571}
 {'label': 'close drawer', 'start_frame': 1607, 'end_frame': 1649}
 {'label': 'cut cake in pieces', 'start_frame': 1723, 'end_frame': 2105}
 {'label': 'open cupboard', 'start_frame': 2133, 'end_frame': 2159}
 {'label': 'close cupboard', 'start_frame': 2159, 'end_frame': 2199}
 {'label': 'open cupboard', 'start_frame': 2223, 'end_frame': 2253}
 {'label': 'close cupboard', 'start_frame': 

Unroll videos using the format indicated in the constructor (This may take a while):
- By default, all videos are unrolled and if the frames already exists, they are not overwritten
- In order to unroll only one video, you can use the parameter video=X
- If you want to overwrite the existing frames, you have to use force=True

If the videos are not unrolled before getting the individual frames, then they will be automatically unrolled when you try to get the frames.

In [46]:
aik.unroll_videos()
#aik.unroll_videos(force=True)             # Force to overwrite unrolled frames
#aik.unroll_videos(video=2)                # Unroll only video 2
#aik.unroll_videos(force=True, video=2)    # Force to overwrite frames of video 2 if they already exist

The videos are already unrolled. If you want to unroll them again and overwrite the current frames, please use the option force=True


Get images from 12 cameras for frame 1.


In [47]:
print(aik.get_images_in_frame(1))

Searching for images of frame  1 ...
Frame name: frame000000001.png
Images of frame  1  retrieved.
[array([[[115, 110, 105],
        [115, 110, 105],
        [113, 108, 103],
        ...,
        [117, 113,  94],
        [117, 113,  94],
        [117, 113,  94]],

       [[115, 110, 105],
        [115, 110, 105],
        [113, 108, 103],
        ...,
        [117, 113,  94],
        [117, 113,  94],
        [117, 113,  94]],

       [[115, 110, 105],
        [115, 110, 105],
        [113, 108, 103],
        ...,
        [117, 113,  94],
        [117, 113,  94],
        [117, 113,  94]],

       ...,

       [[106, 101,  98],
        [106, 101,  98],
        [106, 101,  98],
        ...,
        [161, 157, 141],
        [161, 157, 141],
        [161, 157, 141]],

       [[106, 101,  98],
        [106, 101,  98],
        [106, 101,  98],
        ...,
        [161, 157, 141],
        [161, 157, 141],
        [161, 157, 141]],

       [[106, 101,  98],
        [106, 101,  98],
        [106